version: '3.3'
services:
  app:
    build: .
    ports:
      - 9898:8080
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: bdasignatura

  mongo:
    image: mongo
    container_name: asignaturacontainer
    restart: always

    ports:
      - 27024:27017


volumes:
  mongo-data: